const characters = [
    {
        "Name": "Xborg",
        "Skins": "5",
        "Role": "Figther",
        "Age": "26",
        "Specialties": "Regen, Burst", 
        "img": "https://rare-gallery.com/uploads/posts/341984-X-Borg-Blue-Storm-Skin-Mobile-Legends-Bang-Bang-ML-MLBB-Video-Game.jpg",
    },
    {
        "Name": "Tigreal",
        "Skins": "5",
        "Role": "Tank, Support",
        "Age": "ancient",
        "Specialties": "Crowd Control",
        "img": "https://i0.wp.com/1.bp.blogspot.com/-vllHXhtyNPI/XrOAhWcMtKI/AAAAAAAACaU/TLua-_XQCWQFBcVd3VbfETWFAq2bLrc9wCLcBGAsYHQ/s1600/wallpaper-tigreal-lighborn-defender-skin-mobile-legends-hd-for-pc-hobigame.net.jpg?w=788&ssl=1",
    },
    {
        "Name": "Angela",
        "Skins": "8",
        "Role": "Support",
        "Age": "16",
        "Specialties": "Guard, Support",
        "img": "https://cdn.idntimes.com/content-images/community/2018/10/angela-bunny-love-9dcd0715d42e518898623b05ed6f7212_600x400.jpg",
    },
    {
        "Name": "Hylos",
        "Skins": "4",
        "Role": "Tank",
        "Age": "ancient",
        "Specialties": "Initiator, Guard ",
        "img": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGwlS9pp5p0OkH_dDRNBGYPfro4K46dvyj16oLQrn4j5ROAV1DT2wXc8zrEJQnmnhv61g&usqp=CAU",
    },
    {
        "Name": "Gatotkaca",
        "Skins": "5",
        "Role": "Tank, Figther ",
        "Age": "?",
        "Specialties": "Crowd Control, Brust",
        "img": "https://c4.wallpaperflare.com/wallpaper/239/625/228/mobile-legends-gatotkaca-mighty-legend-hd-wallpaper-preview.jpg",
    },
    {
        "Name": "Uranus",
        "Skins": "6",
        "Role": "Tank",
        "Age": "1 billion years old",
        "Specialties": "Regen",
        "img": "https://i.pinimg.com/originals/02/4a/d4/024ad454c6e662d6d46e4eb5bb8786ea.jpg",
    },
    {
        "Name": "Odette",
        "Skins": "6",
        "Role": "Mage",
        "Age": "26 years old",
        "Specialties": "Brust, Poke",
        "img": "https://w0.peakpx.com/wallpaper/944/702/HD-wallpaper-odette-s-butterfly-goddess-skin-mobile-legends.jpg",
    },
    {
        "Name": "Franco",
        "Skins": "7",
        "Role": "Tank, Support",
        "Age": "40 years old",
        "Specialties": "Initiator, control",
        "img": "https://i.pinimg.com/originals/13/c2/3f/13c23fccfd8c675e4dba48d9c9cd70ee.jpg",
    },
]